import type { Metadata } from "next";
import { Inter, Teko } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { CustomCursor } from "./components/CustomCursor";
import { Cursor } from "./components/Cursor";
import CursorContextProvider, {
  CursorContext,
} from "./providers/CursorContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tekoInit = Teko({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-teko",
  weight: "300",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full h-full bg-neutral-800 text-white ${tekoInit.className}`}
      >
        <CursorContextProvider>
          <Cursor />
          <Navbar />
        </CursorContextProvider>

        {children}
      </body>
    </html>
  );
}
